services:
  - type: web
    name: media-api
    runtime: dotnet7       # Use dotnet7 (not 'dotnet' or 'dotnet8')
    plan: free
    branch: videorefactor
    buildCommand: dotnet restore && dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/FunctionalitiesWebAPI.dll
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
